// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH8HkfeVPOKpUlLKLmjSiO-QrWmbTwWYk',
    appId: '1:646429198693:web:ffe0c734c5bb25f13f798c',
    messagingSenderId: '646429198693',
    projectId: 'socialmedia-2004',
    authDomain: 'socialmedia-2004.firebaseapp.com',
    storageBucket: 'socialmedia-2004.appspot.com',
    measurementId: 'G-B3M99TCGJ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG6K2Zt6KFQwivjPrn2eDIQ2Udyo8W6m0',
    appId: '1:646429198693:android:d14c498af1c9b36d3f798c',
    messagingSenderId: '646429198693',
    projectId: 'socialmedia-2004',
    storageBucket: 'socialmedia-2004.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa8JmMTpZ-XeGZFCSWQ5Pyy0nLu9MmNXA',
    appId: '1:646429198693:ios:3373bf13da17332d3f798c',
    messagingSenderId: '646429198693',
    projectId: 'socialmedia-2004',
    storageBucket: 'socialmedia-2004.appspot.com',
    iosBundleId: 'com.example.sm',
  );
}
